version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    environment:
      - PORT=${PORT:-8000}
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    environment:
      - VITE_API_URL=${BACKEND_URL:-http://localhost:8000}
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped